In [5]:
import numpy as np
x = [[34,56,78],[13,56,43],[56,78,65]]
y = np.array(x)
print(y)

[[34 56 78]
 [13 56 43]
 [56 78 65]]


In [ ]:
y.shape

In [ ]:
y.ndim

In [ ]:
np.zeros([3,3])

In [ ]:
np.ones([3,6])

In [ ]:
np.eye(5,6)

In [ ]:
x = np.diag([13,34,56])
print(np.diag(x))

In [ ]:
np.random.seed(4)
np.random.randint(1,50,8)


In [ ]:
np.random.randn(5)

In [1]:
a = []
size = int(input("Enter the size "))
for i in range(size):
    val = input("Enter the numbers")
    a.append(val)
arr = np.array(a)
for i in range(arr.size):
    print(a[i],end=")")    

NameError: name 'np' is not defined

In [54]:
import numpy as np
matrix = []
row = int(input("Enter the row"))
col = int(input("Enter the col"))
for i in range(row):
    a = []
    for j in range(col):
        val = (input("Enter the number "))
        a.append(val)
    matrix.append(a)
arr = np.array(matrix)   
for i in range(row):
    for j in range(col):
        print(arr[i][j],end="")
print() 
            


456784568


In [6]:
np.__version__

'1.22.0'

In [9]:
x = np.arange(9).reshape(3,3)

In [10]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
x[0:2,0:3]

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
np.identity(5,)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])