In [4]:
import scipy

In [6]:
scipy.__version__

'1.7.3'

derivative of the function

In [17]:
from scipy.misc import derivative
def my_function(x):
    return x**3 + x**2 + x + 1



derivative(func = my_function , x0=2)    

    

18.0

In [20]:
derivative(func = my_function , x0=2,n= 2)    

14.0

permutation Combination

In [23]:
from scipy.special import perm
per = perm(4,3)
print(per)

24.0


Analog 

In [28]:
from scipy import linalg
import numpy as np
matrix = np.array([[3,4,5],[4,7,8],[9,8,6]])
matrix

array([[3, 4, 5],
       [4, 7, 8],
       [9, 8, 6]])

In [33]:
linalg.inv(matrix)

array([[ 0.75862069, -0.55172414,  0.10344828],
       [-1.65517241,  0.93103448,  0.13793103],
       [ 1.06896552, -0.4137931 , -0.17241379]])

In [29]:
linalg.det(matrix)

-28.999999999999996

In [31]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix1

array([[1, 2],
       [3, 4]])

In [32]:
linalg.det(matrix1)

-2.0