In [ ]:
import numpy as np
a = np.random.seed(5)
arr = np.random.randint(1,100,10)
print(arr)


Creating a 2D Array


In [1]:
import numpy as np
matrix = []
row = int(input("Enter the Number of Rows : "))
col = int(input("Enter the Number of Columns : "))
for i in range(row):
    a = []
    for j in range(col):
        val = int(input("Enter the Number : "))
        a.append(val)
    matrix.append(a)
arr = np.array(matrix)
for i in range(row):
    for j in range(col):
        print(arr[i][j],end="")
    print()
print(type(arr))            

ValueError: invalid literal for int() with base 10: ''

Slicing Over 2D Array

In [ ]:
import numpy as np
b = np.random.seed(1)
a = np.random.randint(1,30,9)
x = a.reshape(3,3)
print(x)


In [1]:
import numpy as np
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [ ]:
import numpy as np
a = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a)
print(a[:2,1:3])
b = a[1:,:2]
print(b)
c =a[1:2,1:2]
print(c)
d = a[2:,2:]
print(d)
e = a[2:,:1]
print(e)



In [ ]:
import numpy as np
np.random.seed(111)
a = np.random.randint(1,500,30).reshape(6,5)
print(a)
print(a[2:4,1:3])
print(a[4:6,1:4])
print(a[3:4,2:6])



Numpy View & Copy

In [ ]:
import numpy as np 
np.random.seed(3)
a = np.random.randint(1,30,12).reshape(3,4)
print(a)
slice = a[1:2,0:].copy() # helps to perform crud operationn the the particular part
print(slice)
slice[:] = 0
print(a)


Conditional selection or Operation

In [ ]:
import numpy as np
arr1 = np.array([1,2,3,4]).reshape(2,2)
arr2 = np.array([5,6,7,8]).reshape(2,2)
print(arr1)
print(arr2)
c = arr1+arr2
print("Addition =  ", c)
d = arr2 - arr1
print("Subtraction = ", d)
print(e)




Dot product as a Multiplication

In [3]:
np.random.seed(2)
x = np.array([2,3,4,5]).reshape(2,2)
y = np.array([1,4,3,2]).reshape(2,2)


In [4]:
print(x)

[[2 3]
 [4 5]]


In [5]:
print(y)

[[1 4]
 [3 2]]


In [6]:
print(x.dot(y))

[[11 14]
 [19 26]]


Stack Function Hstack $ VStack in 1D

In [7]:
np.hstack((x,y))


array([[2, 3, 1, 4],
       [4, 5, 3, 2]])

In [8]:
np.vstack((x,y))

array([[2, 3],
       [4, 5],
       [1, 4],
       [3, 2]])

Stack Operation in 2D

In [9]:
import numpy as np 
np.random.seed(122)
a = np.random.randint(1,21,9).reshape(3,3)
b = np.random.randint(31,51,9).reshape(3,3)
print(a)
print(b)


[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
[[40 37 45]
 [34 35 50]
 [50 44 31]]


In [10]:
print(np.hstack((a,b)))

[[16 11 13 40 37 45]
 [17 13 16 34 35 50]
 [ 3 16 11 50 44 31]]


In [11]:
print(np.vstack((a,b)))

[[16 11 13]
 [17 13 16]
 [ 3 16 11]
 [40 37 45]
 [34 35 50]
 [50 44 31]]
