In [2]:
import numpy as np
z = [[2,4,6],[3,2,6],[1,7,9]]
x = np.array(z)
print(x)
print("Total Dimention : ",x.ndim)
print("Shape : ",x.shape)

[[2 4 6]
 [3 2 6]
 [1 7 9]]
Total Dimention :  2
Shape :  (3, 3)


In [4]:
import numpy as np 
x = np.zeros((3,6))
print(x.shape)
print(x)

(3, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
import numpy as np 
x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# eye function  make digonal values as 1 and rest as 0
import numpy as np 
x = np.eye((3))
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#insert  user Choice Diagonal Elements
import numpy as np
z = np.diag([100,200,300])
print(z)

In [7]:
import numpy as np 
x = np.diag([2,3,4,5])
print(np.diag(x))

[2 3 4 5]


In [8]:
import numpy as np 
x = np.random.randint(1,10,3)
print(x)

[8 5 9]


In [9]:
# This is use to Randomly generate a number from 0 to 1
r = np.random.rand(5)
print(r)

[0.00744889 0.9101772  0.74320945 0.33077859 0.57827705]


In [ ]:
# this will create a Random Numbers near 0 (zero)
r = np.random.randn(3)
print(r)

Lets Look How to Perform the Slicing and Indexing

In [ ]:
#How to Find the the size of an array 

import numpy as np
a = []
size = int(input(" Enter the Size : "))
for i in range(size):
    val = int(input("Enter the Values : "))
    a.append(val)
    arr = np.array(a)
for i in range(arr.size):
     print(arr[i],"",end="")


Lets Find the sum of the numbers using the above code

In [11]:
import numpy as np
a = []
size = int(input(" Enter the Size : "))
for i in range(size):
    val = int(input("Enter the Values : "))
    a.append(val)
    arr = np.array(a)
for i in range(arr.size):
     print(arr[i],"",end="")
sum = 0
for i in range(arr.size):
    sum = sum +arr[i]
print("Sum : ",sum)

4 1 6 Sum :  11


Slicing over the Same Programe


In [13]:
import numpy as np
a = []
size = int(input(" Enter the Size : "))
for i in range(size):
    val = int(input("Enter the Values : "))
    a.append(val)
arr = np.array(a)
for i in range(arr.size):
     print(arr[i])
sum = 0     
for i in range(arr.size):
    sum =sum +arr[i]   
print("Sum : ",sum)      
arr1 = arr[0:]     
print("After Indexing ",arr1)



4
5
6
Sum :  15
After Indexing  [4 5 6]


Reshaping of an Array (Change from 1D to 2D and vice versa)

In [14]:
import numpy as np
a = np.random.randint(1,50,12)
print(a.shape)
arr = a.reshape(2,6)    # Here we Converted the 1D to 2D
arr

(12,)


array([[27, 17, 40, 21,  1, 16],
       [48, 29, 34, 15, 39, 48]])

In [ ]:
import numpy as np
a = np.random.randint(1,50,12)

arr = a.reshape(2,6)      # Here we Converted the 1D to 2D
arr
arr1 = arr.reshape(12,)  # Here we convert 2D to 1D
arr1

In [15]:
a = np.random.randint(1,30,8)
y = a.reshape(-1,4)
print(y)
print("The Dimention of an Array : ",y.ndim)
print("The shape of an Array : ",y.shape)


[[ 9 26 16 19]
 [ 9 25 25 15]]
The Dimention of an Array :  2
The shape of an Array :  (2, 4)
